platform :ios, '12.0'

use_frameworks!

target 'MarvelAPI_Example' do
  pod 'MarvelAPI', :path => '../'
  pod 'SwiftLint', '~> 0.39.2'

  target 'MarvelAPI_Tests' do
    inherit! :search_paths

    
  end
end
